### ISSUE TITLE
ng4DCLaunchSiteRgn=>yf5_VehicleSalesRegions transformation is not working

### ISSUE THREAD

**Issue by premshankar1** [sandeepmohan23/yfai_data_migration#28]
In the transformed file, the attribute yf5_VehicleSalesRegions is missing.

In Conversion.xml, both Ng4_MasterPrg and Ng4_PWP map to A9_ProgramItem. And for their revisions, ng4DCLaunchSiteRgn and ng4Business respectively, map to yf5_VehicleSalesRegions. Is this why it is ignoring this mapping? Is there a solution/workaround to this? The problem file is attached and a lookup file - email_userid.csv is attached.
[ALL_NG4_PRG_MASTERPRG_PWP_Phase0_ITEMS_39.zip](https://github.com/sandeepmohan23/yfai_data_migration/files/1130019/ALL_NG4_PRG_MASTERPRG_PWP_Phase0_ITEMS_39.zip)

**Comment by Siemens-PLM** [comment]
@premshankar1 yes that's why it's failing...

What the script says is to map ng4DCLaunchSiteRgn to yf5_VehicleSalesRegions from Ng4_MasterPrg... then you're telling it to map ng4Business to  yf5_VehicleSalesRegions from Ng4_PWP all from A9_ProgramItem.

So basically you're doing:

Ng4_MasterPrg->A9_ProgramItem

A9_ProgramItem>A9_ProgramItem
ng4DCLaunchSiteRgn to yf5_VehicleSalesRegions (yf5_VehicleSalesRegions has been created on A9_ProgramItemRevision **only from Ng4_MasterPrg**)

then

Ng4_PWP->A9_ProgramItem (Now you just combined two different classes into one. Ng4_MasterPrg + Ng4_PWP = A9_ProgramItem)  

A9_ProgramItem>A9_ProgramItem
ng4Business to yf5_VehicleSalesRegions (ng4Business only exists on the objects than came from Ng4_PWP so when you're trying to reference an object from Ng4_MasterPrg, ng4Business will not exists... So basically you are setting yf5_VehicleSalesRegions to null which means delete)

I'm not sure how you supposed to be combining two different values into 1 though. Doesn't seem to make sense to me...

**Comment by premshankar1** [comment]
Thanks, @mike-germano for the explanation. The business requirement is pretty simple - they would like to combine two classes into A9_ProgramItem, and different attributes from the two classes map to the same attribute on the target class.

I will try with a null check on the second map - ng4Business, ie, map to yf5_VehicleSalesRegions only if ng4Business is non-null.

**Comment by premshankar1** [comment]
Tested OK.
